discord:
  bot:
    redirect_uri: https://discord.com/api/oauth2/authorize?client_id=${DISCORD_CLIENT_ID}&permissions=1841683649&scope=bot
    token: ${DISCORD_TOKEN}
    prefix: /
github:
  mark_uri: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  logo_uri: https://github.githubassets.com/images/modules/logos_page/GitHub-Logo.png
  repository:
    uri: https://github.com/frantjc/dillo-bot
    api: https://api.github.com/repos/frantjc/dillo-bot
    token: ${GITHUB_TOKEN}
server:
  port : 8081
flyway:
  driver: com.mysql.cj.jdbc.Driver
  url: ${DB_URI}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  locations: classpath:/db/migration
  outOfOrder: true
  baselineOnMigrate: true
  validateOnMigrate: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URI}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2
  # datasource:
  #   url: jdbc:h2:mem:testdb
  #   driver-class-name: org.h2.Driver
  #   username: sa
  #   password:
  # jpa:
  #   database-platform: org.hibernate.dialect.H2Dialect


