discord:
  bot:
    redirect_uri: https://discord.com/api/oauth2/authorize?client_id=730190921236480051&permissions=1841683649&scope=bot
    token: NzMwMTkwOTIxMjM2NDgwMDUx.XwUrPA.0S5nYMDdgUH7SawS91k6bH1sAYI
    prefix: /
github:
  mark_uri: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  logo_uri: https://github.githubassets.com/images/modules/logos_page/GitHub-Logo.png
  repository:
    uri: https://github.com/frantjc/dillo-bot
    api: https://api.github.com/repos/frantjc/dillo-bot
    token: 7241043a906094b9ce8c3dcabbd3a0c3bb023306

