discord:
  bot:
    redirect_uri: https://discord.com/api/oauth2/authorize?client_id=730190921236480051&permissions=1841683649&scope=bot
    token: NzMwMTkwOTIxMjM2NDgwMDUx.XwY13A.9YyzNX3V7gaVFHohuQF4eehwrTU
    prefix: /
github:
  mark_uri: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  logo_uri: https://github.githubassets.com/images/modules/logos_page/GitHub-Logo.png
  repository:
    uri: https://github.com/frantjc/dillo-bot
    api: https://api.github.com/repos/frantjc/dillo-bot
    token: 8fc48a2e6f41d4798b2bb95bdd869df585258c40
server:
  port : 8081
