resource_types:
  - name: discord-resource
    type: registry-image
    source:
      repository: trivigy/discord-resource

resources:
  - name: dillo-bot
    type: git
    source:
      uri: ((github.uri))
      branch: ((github.branch))
  - name: discord-notify
    type: discord-resource
    source:
      token: ((concourse.discord.token))

env_vars: &env_vars
  DISCORD_TOKEN: ((discord.token))
  DISCORD_CLIENT_ID: ((discord.client.id))
  GITHUB_TOKEN: ((github.branch))

jobs:
  - name: dillo-bot
    plan:
      - get: dillo-bot
      - task: test-bot
        params: *env_vars
        file: dillo-bot/cicd/tasks/test-bot.yml
        on_failure:
          put: discord-notify
          params:
            channel: "((discord.channel.id))"
            title: FAIL
            message: |
              New DilloBot failed his tests
      - task: build-bot
        params: *env_vars
        file: dillo-bot/cicd/tasks/build-bot.yml
        on_failure:
          put: discord-notify
          params:
            channel: "((discord.channel.id))"
            title: FAIL
            message: |
              New DilloBot could not be built
      - task: stop-bot
        file: dillo-bot/cicd/tasks/stop-bot.yml
        on_failure:
          put: discord-notify
          params:
            channel: "((discord.channel.id))"
            title: FAIL
            message: |
              Previous DilloBot refused to die
      - task: start-bot
        file: dillo-bot/cicd/tasks/start-bot.yml
        on_failure:
          put: discord-notify
          params:
            channel: "((discord.channel.id))"
            title: FAIL
            message: |
              New DilloBot was failed to start
        on_success:
          put: discord-notify
          params:
            channel: "((discord.channel.id))"
            title: Success
            message: |
              New DilloBot up and running!