# var_sources:
#   - name: dummy
#     type: dummy
#     config:
#       vars:
#         discord-token: ((discord.token))
#         discord-channel-id: ((discord.channel.id))
#         github-uri: ((github.uri))
#         github-branch: ((github.branch))

resource_types:
  - name: discord-resource
    type: registry-image
    source:
      repository: trivigy/discord-resource

resources:
  - name: dillo-bot
    type: git
    source:
      uri: ((github.uri))
      branch: ((github.branch))
  - name: discord-notify
    type: discord-resource
    source:
      token: ((discord.token))

jobs:
  - name: where-am-i
    plan:
      - get: dillo-bot
      - task: where-am-i
        file: dillo-bot/cicd/tasks/where-am-i.yml
      - get: dillo-bot
      - task: test-bot
        file: dillo-bot/cicd/tasks/test-bot.yml
        on_failure:
          put: discord-notify
          params:
            channel: ((discord.channel.id))
            title: FAIL
            message: |
              New DilloBot failed his tests
      - task: build-bot
        file: dillo-bot/cicd/tasks/build-bot.yml
        on_failure:
          put: discord-notify
          params:
            channel: ((discord.channel.id))
            title: FAIL
            message: |
              New DilloBot could not be built
      - task: stop-bot
        file: dillo-bot/cicd/tasks/stop-bot.yml
        on_failure:
          put: discord-notify
          params:
            channel: ((discord.channel.id))
            title: FAIL
            message: |
              Previos DilloBot refused to die
      - task: start-bot
        file: dillo-bot/cicd/tasks/start-bot.yml
        on_failure:
          put: discord-notify
          params:
            channel: ((discord.channel.id))
            title: FAIL
            message: |
              New DilloBot was failed to start
        on_success:
          put: discord-notify
          params:
            channel: ((discord.channel.id))
            title: Success
            message: |
              New DilloBot up and running!