resource_types:
  - name: discord-resource
    type: registry-image
    source:
      repository: trivigy/discord-resource

resources:
  - name: dillo-bot
    type: git
    icon: github
    source:
      uri: ((github.uri))
      branch: ((github.branch))
  - name: notify
    type: discord-resource
    icon: discord
    source:
      token: ((concourse.discord.token))
  # - name: dillo-bot-image
  #   type: docker-image
  #   icon: docker
  #   source: 
  #     email: ((docker.email))
  #     username: ((docker.username))
  #     password: ((docker.password))
  #     repository: ((docker.username))/dillo-bot-image

anchors:
  - env_vars: &env_vars
    DISCORD_TOKEN: ((discord.token))
    DISCORD_CLIENT_ID: ((discord.client.id))
    GITHUB_TOKEN: ((github.token))

jobs:
  - name: test-dillo-bot
    plan:
      - get: dillo-bot
        trigger: true
      - task: unit-test
        file: dillo-bot/cicd/tasks/test-dillo-bot.yml
        params: *env_vars
    on_failure:
      put: notify
      params:
        channel: ((concourse.discord.channel))
        title: FAIL
        message: |
          The new DilloBot failed his tests!
  - name: dillo-bot-image
    plan:
      - get: dillo-bot
        trigger: true
        passed: [test-dillo-bot]
      - task: cp-dockerfile-to-root
        file: dillo-bot/cicd/tasks/cp-dockerfile-to-root.yml
      - task: receive-dockerfile
        file: dillo-bot/cicd/tasks/receive-dockerfile.yml
      # - put: dillo-bot-image
      #   inputs:
      #     - name: dillo-bot-dockerfile
      #   params:
      #     build: dillo-bot/