resource_types:
  - name: discord-resource
    type: registry-image
    source:
      repository: trivigy/discord-resource

resources:
  - name: dillo-bot
    type: git
    icon: github
    source:
      uri: ((github.uri))
      branch: ((github.branch))
  - name: notify
    type: discord-resource
    icon: discord
    source:
      token: ((concourse.discord.token))
  - name: dillo-bot-image
    type: docker-image
    icon: docker
    source: 
      email: ((docker.email))
      username: ((docker.username))
      password: ((docker.password))
      repository: ((docker.username))/dillo-bot-image

anchors:
  - set_pipeline_vars: &set_pipeline_vars
    github: ((github))
    discord: ((discord))
    concourse: ((concourse))
    docker: ((docker))
  - env_vars: &env_vars
    DISCORD_TOKEN: ((discord.token))
    DISCORD_CLIENT_ID: ((discord.client.id))
    GITHUB_TOKEN: ((github.token))

jobs:
  - name: update-pipeline
    plan:
      - get: dillo-bot
        trigger: true
      - set_pipeline: dillo-bot
        file: dillo-bot/cicd/pipelines/pipeline.yml
        vars: *set_pipeline_vars
  - name: dillo-bot-image
    plan:
      - get: dillo-bot
        trigger: true
      - put: dillo-bot-image
        params:
          build: dillo-bot/cicd/docker
  - name: test-dillo-bot
    plan:
      - get: dillo-bot-image
        trigger: true
    on_failure:
      put: notify
      params:
        channel: ((concourse.discord.channel))
        title: FAIL
        message: |
          The new DilloBot failed his tests!