resource_types:
  - name: discord-resource
    type: registry-image
    source:
      repository: trivigy/discord-resource



resources:
  - name: dillo-bot
    type: git
    icon: github
    source:
      uri: ((github.uri))
      branch: ((github.branch))

  - name: notify
    type: discord-resource
    icon: discord
    source:
      token: ((concourse.discord.token))

  - name: dillo-bot-bucket
    type: s3
    icon: aws
    source:
      bucket: dillo-bot-bucket
      regexp: dillo-bot*.jar

  - name: dillo-bot-image
    type: docker-image
    icon: docker
    source: 
      email: ((docker.email))
      username: ((docker.username))
      password: ((docker.password))
      repository: ((docker.username))/dillo-bot-image

  - name: version
    type: semver
    source:
      initial_version: 0.0.1
      driver: git
      uri: ((github.uri))
      branch: ((github.branch))
      file: cicd/version



build_log_retention: &build_log_retention
  days: 1
  builds: 10
  minimum_succeeded_builds: 1

env_vars: &env_vars
  DISCORD_TOKEN: ((discord.token))
  DISCORD_CLIENT_ID: ((discord.client.id))
  GITHUB_TOKEN: ((github.token))



jobs:
  - name: update-pipeline
    build_log_retention: *build_log_retention
    plan:
      - get: dillo-bot
        trigger: true

      - task: create-vars
        file: dillo-bot/cicd/tasks/create-vars.yml
        params:
          CONCOURSE_DISCORD_TOKEN: ((concourse.discord.token))
          CONCOURSE_DISCORD_CHANNEL: ((concourse.discord.channel))
          DISCORD_TOKEN: ((discord.token))
          DISCORD_CLIENT_ID: ((discord.client.id))
          GITHUB_URI: ((github.uri))
          GITHUB_BRANCH: ((github.branch))
          GITHUB_TOKEN: ((github.token))
          DOCKER_EMAIL: ((docker.email))
          DOCKER_USERNAME: ((docker.username))
          DOCKER_PASSWORD: ((docker.password))

      - set_pipeline: dillo-bot 
        file: dillo-bot/cicd/pipelines/pipeline.yml
        var_files:
          - vars/set_pipeline-vars.yml


  - name: test-dillo-bot
    build_log_retention: *build_log_retention
    plan:
      - get: dillo-bot
        trigger: true

      - task: unit-test
        file: dillo-bot/cicd/tasks/unit-test.yml
        params: *env_vars
        on_failure:
          put: notify
          params:
            channel: ((concourse.discord.channel))
            title: FAIL
            message: |
              The new DilloBot failed his tests


  - name: build-dillo-bot
    build_log_retention: *build_log_retention
    plan:
      - get: dillo-bot
        passed: [test-dillo-bot]

      - get: version
        params:
          bump: patch

      - task: build-jar
        file: dillo-bot/cicd/tasks/build-jar.yml
        params: *env_vars
        on_failure:
          put: notify
          params:
            channel: ((concourse.discord.channel))
            title: FAIL
            message: |
              Failed to build new DilloBot
      
      - put: version
        params:
          file: version/cicd/version

      - put: dillo-bot-bucket
        params:
          file: target/dillo-bot*.jar


  - name: containerize-dillo-bot
    build_log_retention: *build_log_retention
    plan:
      - get: dillo-bot-bucket
        passed: [build-dillo-bot]
        on_failure:
          do:
            - get: dillo-bot
            - put: notify
              params:
                channel: ((concourse.discord.channel))
                title: FAIL
                message: |
                  Failed to pull DilloBot jar from s3, building container from source
            - task: cp-dockerfile-to-root
              file: dillo-bot/cicd/tasks/cp-dockerfile-to-root.yml
            - put: dillo-bot-image
              params:
                build: dillo-bot-dockerfile/