---
platform: linux

image_resource:
    type: registry-image
    source:
        repository: openjdk
        tag: 11.0.7-jdk-slim

inputs:
    - name: dillo-bot

outputs:
    - name: target

caches:
    - path: .m2/

run:
    path: /bin/bash
    args:
        - "dillo-bot/cicd/scripts/build-dillo-bot.sh"