---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: frantjc/dillo-bot-resource

params:
  DISCORD_TOKEN:
  DISCORD_CLIENT_ID:
  GITHUB_TOKEN:

inputs:
  - name: dillo-bot
  - name: version
  - name: build

outputs:
  - name: target

run:
  path: /bin/bash
  args:
    - "dillo-bot/cicd/scripts/build-jar.sh"
        