---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: frantjc/dillo-bot-resource

inputs:
  - name: dillo-bot

outputs:
  - name: build

caches:
  - path: dillo-bot/node_modules

run:
  path: /bin/bash
  args:
    - "dillo-bot/cicd/scripts/build-ui.sh"
        