---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: openjdk

inputs:
  - name: dillo-bot

outputs:
  - name: target

caches:
  - path: .m2/

run:
  path: /bin/sh
  args: ["dillo-bot/cicd/tasks/build-bot.sh"]