---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: debian
    tag: buster-slim

inputs:
  - name: dillo-bot

outputs:
  - name: dillo-bot-dockerfile

run:
  path: /bin/bash
  args:
    - "dillo-bot/cicd/scripts/copy-src-dockerfile-to-root.sh"
