---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ubuntu

inputs:
  - name: dillo-bot

outputs:
  - name: dillo-bot-dockerfil

run:
  path: /bin/bash
  args:
    - "dillo-bot/cicd/scripts/cp-dockerfile-to-root.sh"