---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: debian
    tag: buster-slim

params:
  ENV:

inputs:
  - name: dillo-bot
  - name: version

outputs:
  - name: tags

run:
  path: /bin/bash
  args:
    - "dillo-bot/cicd/scripts/create-image-tags.sh"