---
platform: linux

image_resource:
    type: registry-image
    source:
        repository: ubuntu

outputs:
    - name: vars

run:
    path: /bin/bash
    args:
        - "dillo-bot/cicd/scripts/create-vars.sh"