---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: alpine

params:
  ENV:

inputs:
  - name: dillo-bot
  - name: version

outputs:
  - name: tags

run:
  path: /bin/sh
  args:
    - "dillo-bot/cicd/scripts/create-image-labels.sh"