---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: debian
    tag: stable-slim

params:
  ENV:

inputs:
  - name: dillo-bot
  - name: dillo-bot-bucket
  - name: version

outputs:
  - name: globs

run:
  path: /bin/bash
  args:
    - "dillo-bot/cicd/scripts/create-release-globs.sh"
