---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: debian
    tag: stable-slim

params:
  ENV:

inputs:
  - name: dillo-bot

outputs:
  - name: commitish

run:
  path: /bin/bash
  args:
    - "dillo-bot/cicd/scripts/create-release-commitish.sh"
