---
platform: linux

image_resource:
    type: registry-image
    source:
        repository: alpine

params:
    KEY:

inputs:
    - name: dillo-bot

outputs:
    - name: key

run:
    path: /bin/sh
    args:
        - "dillo-bot/cicd/scripts/create-key.sh"
