---
platform: linux

image_resource:
  type: registry-image
  source:
    username: ((docker.username))
    password: ((docker.password))
    repository: ((docker.username))/dillo-bot-resource

inputs:
  - name: linted-dillo-bot

outputs:
  - name: linted-dillo-bot

run:
  path: /bin/bash
  args:
    - "dillo-bot/cicd/scripts/lint-ui.sh"