---
    platform: linux
    
    image_resources:
        type: registry-image
        source:
            repository: ubuntu
    
    inputs:
        - name: dillo-bot-dockerfile
    
    run:
        path: dillo-bot/cicd/scripts/receive-dockerfile.sh