---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: frantjc/general-resource

params:
  URL:

inputs:
  - name: dillo-bot

run:
  path: /bin/bash
  args:
    - "dillo-bot/cicd/scripts/smoke-test.sh"