---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: frantjc/general-resource

params:
  USER:
  PUBLIC_DNS:
  DISCORD_TOKEN:
  GITHUB_TOKEN:
  DISCORD_CLIENT_ID:
  PORT: 8081
  ENV:

inputs:
  - name: key
  - name: dillo-bot

run:
  path: /bin/bash
  args:
    - "dillo-bot/cicd/scripts/ssh-and-start-container.sh"
