---
platform: linux

image_resource:
    type: registry-image
    source:
        repository: kroniak/ssh-client

params:
    USER:
    PUBLIC_DNS:
    DISCORD_TOKEN:
    GITHUB_TOKEN:
    DISCORD_CLIENT_ID:

inputs:
    - name: key
    - name: dillo-bot

run:
    path: /bin/sh
    args:
        - "dillo-bot/cicd/scripts/ssh-and-start-container.sh"
