---
platform: linux

image_resource:
    type: registry-image
    source:
        repository: kroniak/ssh-client

params:
    USER:
    PUBLIC_DNS:

inputs:
    - name: key
    - name: dillo-bot

run:
    path: /bin/sh
    args:
        - "dillo-bot/cicd/scripts/stop-container.sh"