---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: frantjc/openssh-client

params:
  USER:
  PUBLIC_DNS:

inputs:
  - name: key
  - name: dillo-bot

run:
  path: /bin/bash
  args:
      - "dillo-bot/cicd/scripts/ssh-and-stop-container.sh"
