---
platform: linux

image_resource:
    type: registry-image
    source:
        repository: ubuntu

params:
    USER:
    PUBLIC_DNS:

inputs:
    - name: key
    - name: dillo-bot

run:
    path: /bin/bash
    args:
        - "dillo-bot/cicd/scripts/stop-container.sh"