---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: openjdk

inputs:
  - name: dillo-bot

caches:
  - name: dillo-bot

run:
  path: /bin/sh
  args: ["dillo-bot/cicd/tasks/test-bot.sh"]