---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: frantjc/dillo-bot-resource

inputs:
  - name: dillo-bot

run:
  path: /bin/bash
  args:
    - "dillo-bot/cicd/scripts/unit-test-ui.sh"
