---
platform: linux

image_resource:
  type: registry-image
  source:
    username: ((docker.username))
    password: ((docker.password))
    repository: ((docker.username))/dillo-bot-resource
        
params:
  DISCORD_TOKEN:
  DISCORD_CLIENT_ID:
  GITHUB_TOKEN:

inputs:
  - name: dillo-bot

caches:
  - path: .m2/

run:
  path: /bin/bash
  args:
    - "dillo-bot/cicd/scripts/unit-test.sh"
