---
platform: linux

image_resource:
  type: registry-image
  source:
    username: ((docker.username))
    password: ((docker.password))
    repository: ((docker.username))/dillo-bot-resource

inputs:
  - name: dillo-bot

caches:
  - path: dillo-bot/node_modules

run:
  path: /bin/bash
  args:
    - "dillo-bot/cicd/scripts/unit-test-ui.sh"
